spring:
  application:
    name: CRUD_signOk

  # DB Connection
  datasource:
    url: jdbc:postgresql://localhost:5432/userlist
    username: lbg
    password : password
#    driver-class-name: org.postgresql.Driver

# mybatis
mybatis:
#  config: mybatis/mybatis-config.xml
  type-aliases-package: org.example.crud_signok.Template
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    org.example.crud_signok : trace
    org.hibernate.sql: trace
